[build]
  command = "npm run build"
  publish = "dist"

# Proxy intern: /api/* -> site-ul cu funcția
[[redirects]]
  from = "/api/*"
  to = "https://vision-it-mail.netlify.app/api/:splat"
  status = 200
